name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - armv7
          - ppc64le
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Test
        run: |
          sudo ./alpkg init --packager "Your Name <your@email.address>" --aports "https://gitlab.alpinelinux.org/alpine/aports"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: alpkg
